name: my_projects
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  card_swiper: ^1.0.4
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  photo_view: ^0.13.0
  provider: ^6.0.1
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
